name: Tweet nightly

on:
  issues:
    types:
      - labeled
      - closed

jobs:
  dump-contexts:
    if: (github.event.action == 'labeled' && github.event.label.name == 'release-notes/social' && github.event.issue.state == 'closed') || (github.event.action == 'closed' &&  contains(github.event.issue.labels.*.name, 'release-notes/social'))
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
